server:
  port: 8080 #서버가 사용할 포트 번호 설정
  servlet:
    encoding:
      charset: utf-8 #서블릿의 응답과 요청 인코딩을 UTF-8로 설정
      force: true # 요청과 응답에 대해 이 인코딩을 !강제!로 사용하도록 설정합니다.

spring:
  profiles:
    default: secure
  thymeleaf:
    enabled: false
  mvc:
    view:
      prefix: /WEB-INF/view/ # JSP 파일이 위치한 디렉토리 접두사를 설정합니다.
      suffix: .jsp # 뷰 이름에 자동으로 추가될 파일 확장자를 설정합니다.
  servlet:
    multipart:
      max-file-size: 20MB #파일 최대 크기는 20MB로 제한
      max-request-size: 20MB #멀티파트 전체 요청 크기 20MB 제한
  mail:
    host: smtp.gmail.com # Google의 SMTP 
    port: 587 # SMTP ?? ??(Google = 587) 
    username: perfecfolio@gmail.com # 발신자 이메일
    password: tles xqrg qgfk tjin # perfecfolio@gmail.com 의 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true 
          timeout: 5000 # Socket Read Timeout (5)
          starttls:
            enable: true # StartTLS
clova:
  chatbot:
    api-url: "https://p4abd3idfx.apigw.ntruss.com/custom/v1/15674/0c35f8b3e6e0a8b2343d25d43d472dc72e27b0e502c75ec6be34211f36d73eaa"
    client-id: "DZ6JGuseNI8G4K8fyAlt"
    client-secret: "bktDVnllbEJOS2pSQ1VXQUNXdkJRdXBVbnJpSUZXeFk="

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?serverTimezone=Asia/Seoul # 데이터 베이스 연결을 위한 URL을 설정합니다.
    driver-class-name: com.mysql.cj.jdbc.Driver # 드라이버 클래스를 설정합니다.
    username: root # 사용자 ID를 지정
    password: asd123 # DB 비밀번호 여기서는 빈 문자열로 설정
  jpa:
    hibernate:
    ddl-auto: update  # 개발 중일 때는 'update', 배포 시에는 'validate'로 변경
    show-sql: true
    
#  output:
#    ansi:
#      enabled: always # 콘솔 출력에 ANSI 코드를 사용할 수 있도록 설정
      
# Mybatis 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml # MyBatis 매퍼 파일 위치를 설정합니다. **은 모든 디렉토리를 의미하며, *.xml은 모든 xml 파일을 의미합니다.
  configuration:
    map-underscore-to-camel-case: true # 데이터베이스의 언더스코어 네이밍(column_name)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL 로깅 구현체를 설정합니다.


logging:
  config: classpath:logback-spring.xml
  level:
    org.apache.ibatis: DEBUG # MyBatis 로깅 레벨을 DEBUG로 설정하여 실행되는 SQL 쿼리와 내부 로깅 정보를 콘솔에 출력한다.
